const TYPES = {
  SET_IS_LOGIN: "SET_IS_LOGIN",
  SET_TOKEN: "SET_TOKEN",
  SET_IS_AUTHENTICATING: "SET_IS_AUTHENTICATING",
  SET_LEVEL: "SET_LEVEL",
  SET_USERNAME: "SET_USERNAME",
  SET_USER_ID: "SET_USER_ID",
  SET_NAME: "SET_NAME",
  SET_LOGOUT: "SET_LOGOUT"
};

export default TYPES;
